### ISSUE TITLE
PrusaControl won't start

### ISSUE THREAD

**Issue by NLSEngineering** [prusa3d/PrusaControl#83]
here is the contents of the log file.

[ERROR][main.py:95:log_exception()]-Logging an uncaught exception
Traceback (most recent call last):
  File "main.py", line 193, in <module>
  File "main.py", line 159, in main
  File "controller.py", line 65, in __init__
  File "parameters.py", line 356, in __init__
  File "parameters.py", line 459, in download_new_settings_files
  File "json\__init__.py", line 268, in load
  File "json\__init__.py", line 319, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by prusa3d-bb** [comment]
hello
For this you would need to go to prusacontrol.org there is a form on the site for submitting errors as it is in a beta state. 
Thank you 

—
ShaneTechnical Support


PRUSA Research
+420 222 263 718
+421 220 570 305
188/7a Partyzánská, 17000, Prague
shop.prusa3D.com



For simple troubleshooting, please use: http://help.prusa3d.com


Please rate our reply ...be generous :-)

--- original message ---
On Tue, Mar 20, 2018 at 04:45 pm, <notifications@github.com> NLSEngineering wrote:


here is the contents of the log file.

[ERROR][main.py:95:log_exception()]-Logging an uncaught exception

Traceback (most recent call last):

File "main.py", line 193, in 

File "main.py", line 159, in main

File "controller.py", line 65, in init

File "parameters.py", line 356, in init

File "parameters.py", line 459, in download_new_settings_files

File "json_init_.py", line 268, in load

File "json_init_.py", line 319, in loads

File "json\decoder.py", line 339, in decode

File "json\decoder.py", line 357, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---
