### ISSUE TITLE
Ubuntu - PruscaControl stopped working

### ISSUE THREAD

**Issue by marcopiraccini** [prusa3d/PrusaControl#86]
Here the log:
```
⇒ /opt/PrusaControl/PrusaControl_0.9.4_415_beta_64bit.AppImage
/bin/bash: /tmp/.mount_PrusaCbpUqMB/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: /tmp/.mount_PrusaCbpUqMB/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
Traceback (most recent call last):
  File "./PrusaControl-master/main.py", line 193, in <module>
  File "./PrusaControl-master/main.py", line 159, in main
  File "./PrusaControl-master/controller.py", line 65, in __init__
  File "./PrusaControl-master/parameters.py", line 345, in __init__
  File "./usr/lib/python3.4/configparser.py", line 672, in read
  File "./usr/lib/python3.4/configparser.py", line 993, in _read
  File "./usr/lib/python3.4/codecs.py", line 313, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 7: invalid start byte
QThread: Destroyed while thread is still running
```

**Comment by marcopiraccini** [comment]
I solved this, removing `~/.prusacontrol/prusacontrol.cfg` (I see from the code that the error was raised when trying to read this file). 
Leaving this issue open because I don't know how this situation happened.
