### ISSUE TITLE
prusacontrol_0.9.4.415_beta.AppImage refuses to launch on new system

### ISSUE THREAD

**Issue by probonopd** [prusa3d/PrusaControl#92]
prusacontrol_0.9.4.415_beta.AppImage refuses to launch on new system:

```
me@host:~$ /isodevice/Applications/prusacontrol_0.9.4.415_beta.AppImage 
Traceback (most recent call last):
  File "./PrusaControl-master/main.py", line 193, in <module>
  File "./PrusaControl-master/main.py", line 159, in main
  File "./PrusaControl-master/controller.py", line 67, in __init__
  File "./PrusaControl-master/parameters.py", line 65, in __init__
  File "./PrusaControl-master/parameters.py", line 256, in read_material_quality_parameters_for_printer
FileNotFoundError: [Errno 2] No such file or directory: '/home/me/.prusacontrol/data/materials_i3_mk2mm.json'
QThread: Destroyed while thread is still running
Segmentation fault
```

Workaround:

```
me@host:~$ cp /home/me/.prusacontrol/data/materials_i3_mk2.json /home/me/.prusacontrol/data/materials_i3_mk2mm.json 

me@host:~$ cp /home/me/.prusacontrol/data/materials_i3_mk2.json /home/me/.prusacontrol/data/materials_i3_mk3.json 
```

**Comment by mcstoufer** [comment]
New issue with similar issue/fix at https://github.com/prusa3d/PrusaControl/issues/99
